//
// Created by HQ on 2020/9/9.
//
#define IJKMPET_FLUSH 0
#define IJKMPET_ERROR 100
#define IJKMPET_PREPARED 200
#define IJKMPET_COMPLETED 300
#define IJKMPET_VIDEO_SIZE_CHANGED 400
#define IJKMPET_SAR_CHANGED 401
#define IJKMPET_VIDEO_RENDERING_START 402
#define IJKMPET_AUDIO_RENDERING_START 403
#define IJKMPET_VIDEO_ROTATION_CHANGED 404
#define IJKMPET_AUDIO_DECODED_START 405
#define IJKMPET_VIDEO_DECODED_START 406
#define IJKMPET_OPEN_INPUT 407
#define IJKMPET_FIND_STREAM_INFO  408
#define IJKMPET_COMPONENT_OPEN 409
#define IJKMPET_VIDEO_SEEK_RENDERING_START 410
#define IJKMPET_AUDIO_SEEK_RENDERING_START 411
#define IJKMPET_BUFFERING_START 500
#define IJKMPET_BUFFERING_END 501
#define IJKMPET_BUFFERING_UPDATE 502
#define IJKMPET_BUFFERING_BYTES_UPDATE 503
#define IJKMPET_BUFFERING_TIME_UPDATE 504
#define IJKMPET_CURRENT_POSITION_UPDATE 510
#define IJKMPET_SEEK_COMPLETE 600
#define IJKMPET_PLAYBACK_STATE_CHANGED 700
#define IJKMPET_TIMED_TEXT 800
#define IJKMPET_ACCURATE_SEEK_COMPLETE 900
#define IJKMPET_GET_IMG_STATE 1000